import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { assembleUserData } from "@/lib/auth/auth";
import { UserProvider } from "@/lib/auth/UserProvider";
import { QueryProvider } from "./QueryProvider";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDataPromise = await assembleUserData();
  return (
    <html
      lang="en"
      className={`bg-white dark:bg-gray-950 text-black dark:text-white ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-[100dvh] bg-gray-50">
        <QueryProvider>
          <UserProvider userData={userDataPromise}>
            <NuqsAdapter>{children}</NuqsAdapter>
          </UserProvider>
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
